name = "Absynth"
uuid = "198fb612-3ccb-11e9-3f7d-cd8c0d4e7bc8"
authors = ["Andreas Humenberger <ahumenberger@gmail.com>"]
version = "0.3.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
Combinatorics = "0.7.0"
DataFrames = "0.19.4"
DataStructures = "0.17.0"
DynamicPolynomials = "0.3.3"
MacroTools = "0.5.1"
MultivariatePolynomials = "0.3.2"
ParserCombinator = "2.0.0"
ProgressMeter = "1.0.0"
julia = "1.0"
